### ISSUE TITLE
Migrate the tutorial to Fluid

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Tutorial-Templating-Files#1]
The templating tutorial should cover how to create template using FLUIDTEMPLATE.

Similar tutorial (also a little bit outdated):
http://typo3buddy.com/typo3-template-tutorial/fluid/

TS Refercence: 
https://docs.typo3.org/typo3cms/TyposcriptReference/ContentObjects/Fluidtemplate/Index.html#example

**Comment by susannemoog** [comment]
Additionally the templating tutorial should maybe link to the fluid_styled_content manual for using and creating content element templates.

**Comment by sypets** [comment]
I think this can be closed. Please reopen if you do not agree.
